#!/bin/bash
# Devstack settings

# This must not use any variables to work properly in OpenStack's DevStack playbook
define_plugin stx-tis-repo
# This works for Zuul jobs using OpenStack's DevStack roles
plugin_requires stx-tis-repo stx-update
plugin_requires stx-tis-repo stx-integ

STX_TIS_NAME=stx-tis-repo
enable_service $STX_TIS_NAME

# Settings for stx-fault
# Circular dependencies are fun!
# fm-rest-api has an undeclared dependency on cgtsclient from stx-config
# so if that is not present we can't install it
if ! is_service_enabled stx-config; then
    disable_service fm-rest-api
fi
# but fm-rest-api has its own (declared!) external dependencies too
if is_service_enabled fm-rest-api; then
    # stx-update
    enable_service tsconfig
fi

# Initial source of lib script
source $DEST/stx-fault/devstack/lib/stx-fault
